import { z } from "zod";

/**
 * Reusable field schemas
 * (prevents duplication & drift across models)
 */

// ISO datetime string (Date.toISOString())
const IsoDateTimeSchema = z.string().datetime();

// Slug validation used across the app
const SlugSchema = z
  .string()
  .min(2, "Slug must be at least 2 characters")
  .max(100, "Slug must not exceed 100 characters")
  .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, "Slug must be lowercase, alphanumeric, and use hyphens");

// URL validation
const UrlSchema = z.string().url();

/**
 * ============================================
 * Source Schema (API Response)
 * ============================================
 *
 * Represents a publisher (BBC, Reuters, etc.)
 * returned by the API.
 *
 * Dates are strings because JSON does not support Date objects.
 */
export const SourceSchema = z.object({
  id: z.string(),

  name: z.string().min(1),

  slug: SlugSchema,

  websiteUrl: UrlSchema,

  logoUrl: z.string().url().nullable(), // String? in Prisma → string | null

  isActive: z.boolean(),

  createdAt: IsoDateTimeSchema,
  updatedAt: IsoDateTimeSchema,
});

/**
 * TypeScript type inferred from schema
 */
export type Source = z.infer<typeof SourceSchema>;

/**
 * ============================================
 * Create Source Input
 * ============================================
 *
 * Used for POST /sources
 *
 * Fields generated by DB are excluded.
 */
export const CreateSourceSchema = z.object({
  name: z
    .string()
    .min(2, "Name must be at least 2 characters")
    .max(100, "Name must not exceed 100 characters"),

  slug: SlugSchema,

  websiteUrl: UrlSchema,

  logoUrl: z.string().url().nullable().optional(),

  isActive: z.boolean().optional(), // default true in DB
});

export type CreateSourceInput = z.infer<typeof CreateSourceSchema>;

/**
 * ============================================
 * Update Source Input (PATCH)
 * ============================================
 *
 * All fields optional.
 * Requires at least one field.
 */
export const UpdateSourceSchema = z
  .object({
    name: z.string().min(2).max(100).optional(),
    slug: SlugSchema.optional(),
    websiteUrl: UrlSchema.optional(),
    logoUrl: z.string().url().nullable().optional(),
    isActive: z.boolean().optional(),
  })
  .refine((obj) => Object.keys(obj).length > 0, {
    message: "At least one field must be provided",
  });

export type UpdateSourceInput = z.infer<typeof UpdateSourceSchema>;
